### ISSUE TITLE
I can’t import a jellycut into shortcuts without an error

### ISSUE THREAD

**Issue by Quinndevelops** [ActuallyZach/Jellycuts-Issues#139]
Every time o hit the button to make the shortcut it says failed bought before error

**Comment by zhuethanca** [comment]
Same, the export button fails with:
Failed To Sign
Connection Caught Before Failure - Please Try Again.
Please Try Again

**Comment by aviewtoagroove** [comment]
I’ve also been having this issue since last week. The issue seems to occur when the new shortcut is “signed” before being imported into shortcuts.

I’ve tried with scripts I was previously able to import, for which the same error message appears. I’ve also tried re-adding the Jellycuts Helper shortcut to no success.

Im currently running iOS 17.3.1 (21D61) and have the latest version of the app installed (1.4.1).

**Comment by ActuallyTaylor** [comment]
Hey everyone, sorry about this! I am looking into everything now

**Comment by Quinndevelops** [comment]
😀 I’m so happy that you saw the comment you got this I believe you can fix this

**Comment by ActuallyTaylor** [comment]
If you give it a shot now it should all be working!

**Comment by Quinndevelops** [comment]
It worked good job 👍
