### ISSUE TITLE
Documentation search bar extends past left edge of screen on iPad in sidebar

### ISSUE THREAD

**Issue by FifiTheBulldog** [ActuallyZach/Jellycuts-Issues#27]
## Describe the bug
When viewing the documentation in the sidebar on iPad, the search bar extends past the left edge of the screen instead of staying within the visible area.

## To Reproduce
1. Open Jellycuts on iPad
2. Tap on “Home”
3. Tap on the Settings icon
4. Tap on “Documentation”
5. Look at the search bar

## Expected behavior
The search bar’s left and right edges should be neatly aligned with the left and right edges of the list of items.

### Screenshots
![7E2AE852-27F7-495D-B3F1-FBBBC1FF270A](https://user-images.githubusercontent.com/63314105/108671582-b08b9000-74ae-11eb-814c-65f4b0790489.jpeg)

## Information
 - Device: iPad (7th generation)
 - OS: iPadOS 14.4
 - Jellycuts Version: 0.9(15)

### Additional context
I think it would be preferable to always display the popup for the documentation instead of trying to squeeze it into the sidebar. It’s hard to read when it’s in such a narrow space on a big screen.

**Comment by ActuallyZach** [comment]
This has been fixed in the next version. The documentation now opens in a popup with the option to send it too a new window.
![IMG_0055](https://user-images.githubusercontent.com/32944568/108719591-c10f2b00-74ed-11eb-9675-ee18b1058629.PNG)
![IMG_0054](https://user-images.githubusercontent.com/32944568/108719598-c40a1b80-74ed-11eb-9ad6-7344ebe4503d.PNG)
